apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  type: NodePort
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
    name: tcp
  selector:
    app: eureka
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-eureka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: ursuad/tutorial-springbox-eureka:latest
        env:
        - name: APPLICATION_DOMAIN
          value: "eureka"
        ports:
        - containerPort: 8761
        livenessProbe:
            httpGet:
              path: /health
              port: 8761
            initialDelaySeconds: 20
            timeoutSeconds: 1