apiVersion: v1
kind: Service
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  type: NodePort
  ports:
  - port: 7474
    targetPort: 7474
    protocol: TCP
    name: tcp
  selector:
    app: neo4j
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-neo4j
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: ursuad/docker-neo4j:latest
        ports:
        - containerPort: 7474