apiVersion: "v1"
kind: "Service"
metadata:
  name: "api-gateway-frontend"
  labels:
    name: "api-gateway-frontend"
spec:
  type: "LoadBalancer"
  ports:
    -
      port: 9000
      targetPort: 9000
      protocol: "TCP"
  selector:
    app: springbox-springbox-api-gateway
