apiVersion: "v1"
kind: "Service"
metadata:
  name: "catalog-frontend"
  labels:
    name: "catalog-frontend"
spec:
  type: "LoadBalancer"
  ports:
    -
      port: 8080
      targetPort: 8080
      protocol: "TCP"
  selector:
    app: springbox-catalog
