apiVersion: "v1"
kind: "Service"
metadata:
  name: "neo4j-frontend"
  labels:
    name: "neo4j-frontend"
spec:
  type: "LoadBalancer"
  ports:
    -
      port: 7474
      targetPort: 7474
      protocol: "TCP"
  selector:
    app: neo4j
