apiVersion: "v1"
kind: "Service"
metadata:
  name: "reviews-frontend"
  labels:
    name: "reviews-frontend"
spec:
  type: "LoadBalancer"
  ports:
    -
      port: 8081
      targetPort: 8081
      protocol: "TCP"
  selector:
    app: springbox-reviews
