apiVersion: "v1"
kind: "Service"
metadata:
  name: "mongo-frontend"
  labels:
    name: "mongo-frontend"
spec:
  type: "LoadBalancer"
  ports:
    -
      port: 28017
      targetPort: 28017
      protocol: "TCP"
  selector:
    app: mongodb
