apiVersion: "v1"
kind: "Service"
metadata:
  name: "rabbit-frontend"
  labels:
    name: "rabbit-frontend"
spec:
  type: "LoadBalancer"
  ports:
    -
      port: 15672
      targetPort: 15672
      protocol: "TCP"
  selector:
    app: rabbitmq
