apiVersion: "v1"
kind: "Service"
metadata:
  name: "recommendations-frontend"
  labels:
    name: "recommendations-frontend"
spec:
  type: "LoadBalancer"
  ports:
    -
      port: 8082
      targetPort: 8082
      protocol: "TCP"
  selector:
    app: springbox-recommendations
